Whoops Error Fix
On a fresh install of Invoice Ninja I got a Whoops error caused by the deprecation of the current line (1126) being:

`$currencyId = ($client && $client->currency_id) ? $client->currency_id : $this->currency_id ?: DEFAULT_CURRENCY;`

Once changed to this new format, the error went away and I was able to use Invoice Ninja no problem.  Hope it helps!

`$currencyId = ($client && $client->currency_id) ? $client->currency_id : ($this->currency_id ?: DEFAULT_CURRENCY);`

Error for reference!
-------------------------------------------------------------------------
production.ERROR: ***ErrorException*** [0] : /app/Models/Account.php [Line 1126] => Unparenthesized `a ? b : c ?: d` is deprecated. Use either `(a ? b : c) ?: d` or `a ? b : (c ?: d)`